
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[209] =
    {   0,
        1,    1,   32,   30,    1,   29,   30,   30,   15,   15,
       30,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,    1,    0,    0,   17,   16,    0,
        0,   15,    0,    0,    0,   27,   25,   26,   28,    0,
        0,    0,    0,    0,    0,   13,   14,   14,   14,   14,
        2,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,    0,    0,    0,   27,   27,   27,   25,   25,
       25,   26,   26,   26,   28,   28,   28,    0,    0,    0,
        0,   13,   13,   13,   13,   13,   10,   14,   14,    5,
        0,    0,   14,   14,   14,   14,   14,   14,   14,   14,

       14,   14,    0,    0,    0,    0,    0,    0,   13,   13,
       13,    0,    0,    0,   14,    4,    3,    0,    0,   14,
       14,   14,   14,   14,   14,   14,   14,    0,    0,    0,
        0,   11,    0,   13,   13,    0,    0,    0,    0,   14,
        0,    0,   22,   14,   14,    0,    0,    7,    8,    9,
       14,   14,    0,    0,    0,   13,   13,    0,   24,    0,
        0,   14,   14,    0,   20,    0,    0,    6,    0,    0,
       13,   21,   14,   14,    0,    0,    0,    0,   14,   14,
       19,   14,    0,    0,    0,   12,    0,   14,   14,    0,
        0,   18,   14,   14,    0,    0,    0,   14,   14,    0,

        0,    0,   23,    0,   14,   14,   14,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    5,    5,    5,    5,    5,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,    5,    5,
       18,    5,    5,    5,   19,   20,   20,   21,   22,   23,
       24,   20,   25,   20,   20,   26,   20,   27,   28,   29,
       20,   30,   31,   32,   33,   20,   20,   20,   20,   20,
       34,    5,   35,    5,   20,    5,   36,   20,   20,   37,

       38,   39,   40,   20,   41,   20,   20,   42,   20,   43,
       44,   45,   20,   46,   47,   48,   49,   20,   20,   20,
       20,   20,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    2,    1,    3,    4,    4,    5,    6,    7,    7,
        8,    7,    8,    7,    9,    9,    4,   10,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,    7,    4,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11
    } ;

static const flex_int16_t yy_base[231] =
    {   0,
        0,    0,  479,  958,   48,  958,  467,   38,   54,   60,
       77,   78,   88,   97,  112,  118,   94,  116,   36,  102,
       61,  119,  124,  125,  151,  169,  454,  443,   45,  162,
       82,  173,  170,  202,    0,  152,  183,  210,  217,  203,
      220,   49,  225,  198,    0,  267,  169,  170,  211,  216,
      251,  233,  240,  208,  225,  257,  262,  264,  267,  270,
      272,  275,  247,  389,  370,  302,  958,  312,  317,  958,
      320,  327,  958,  335,  342,  958,  345,  360,  350,  375,
      351,  395,   92,  361,  396,  399,  410,  303,  318,  404,
      364,    0,  350,  311,  366,  411,  412,  418,  420,  423,

      392,  425,  338,  314,  451,  350,  125,  455,  134,  461,
      466,  499,  340,  318,  506,  460,  455,  376,  305,  493,
      496,  504,  431,  482,  506,  509,  448,  267,  237,  533,
      195,  264,  536,  539,  544,  257,  216,  173,  174,  579,
      548,  168,  958,  530,  548,  558,  148,  395,  585,  522,
      536,  573,  105,   84,  597,  601,  605,  119,  958,  111,
       92,  575,  587,  611,  958,  620,  202,  614,  604,  233,
      616,  958,  632,  605,   73,   42,   71,  380,  634,  624,
      958,  641,   47,   62,  151,  958,  490,  642,  643,  668,
      267,   51,  644,  653,  670,  680,  686,  669,  671,  702,

      692,  303,  958,  708,  678,  695,  706,  958,  754,  764,
      774,  784,  794,  804,  814,  824,  834,  843,  846,  856,
      867,  877,  883,  893,  903,  910,  921,  930,  937,  946
    } ;

static const flex_int16_t yy_def[231] =
    {   0,
      208,    1,  208,  208,  208,  208,  209,  208,  210,  210,
      211,  212,  212,  212,  212,  212,   16,   16,   16,   16,
       16,   16,   16,   16,  208,  211,  209,  209,  208,  208,
      208,  210,  208,  210,   26,  213,  214,  215,  216,   26,
       26,  208,   26,  208,   34,  217,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,  208,  208,  208,  213,  208,  213,  214,  208,
      214,  215,  208,  215,  216,  208,  216,  208,   26,  218,
       26,  217,  219,   82,   82,   82,  220,   16,   16,   16,
      208,  221,   16,   16,   16,   16,   16,   16,   16,   16,

       16,   16,  208,  208,   26,  218,  218,   26,  219,   82,
       82,  222,  223,   34,  224,   16,   16,  225,  221,   16,
       16,   16,   16,   16,   16,   16,   16,  208,  208,   26,
      218,  218,   26,   82,   82,  208,  226,  208,  223,  224,
      208,  227,  208,   16,   16,  225,  208,   16,   16,   16,
       16,   16,  208,  208,   26,   82,   82,  226,  208,  227,
      208,   16,   16,  208,  208,  208,  208,   16,  208,  208,
       82,  208,   16,   16,  208,  208,  228,  229,   16,   16,
      208,   16,  208,  228,  228,  208,  229,   16,   16,  230,
      228,  228,   16,   16,  208,  230,  230,   16,   16,  230,

      208,  208,  208,  230,   16,   16,   16,    0,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208
    } ;

static const flex_int16_t yy_nxt[1008] =
    {   0,
        4,    5,    6,    5,    4,    7,    4,    4,    4,    4,
        8,    4,    8,    4,    9,   10,    4,   11,   12,   12,
       13,   14,   15,   12,   16,   12,   12,   12,   17,   18,
       12,   12,   12,    4,    4,   12,   19,   20,   21,   12,
       22,   12,   12,   12,   23,   24,   12,   12,   12,   25,
      190,   25,   29,   29,   80,   30,  185,   30,   47,   29,
       29,   30,   47,   30,   31,   26,   31,  185,   32,   32,
       31,   33,   31,   56,   32,   32,  185,   33,   35,   44,
       35,   44,   42,   47,  183,   36,   37,   47,   38,   44,
       39,   44,   45,   45,  190,   46,   29,   29,   44,  183,

       44,   41,   45,   45,   58,   46,   83,   83,  172,   48,
       42,   45,   45,   44,   46,   44,   47,   43,  161,   44,
       47,   44,   49,   53,   47,  113,   45,   45,   47,   46,
      131,  169,   45,   45,   54,   46,  169,   55,   47,   50,
       51,   47,   47,   57,   52,   47,   47,   47,   83,   83,
       47,   47,   25,   66,   25,   66,  191,   51,  192,  132,
       61,   59,   62,   30,  165,   30,   67,   67,   26,   60,
       35,   63,   35,   63,   30,  161,   30,   36,   37,   33,
       38,  138,   39,   31,   69,   31,   69,   32,   32,  159,
       33,   47,   87,   41,   64,   47,   47,   70,   70,   44,

      131,   44,   42,   30,   78,   30,   78,  177,  167,   43,
       65,   72,  208,   72,  208,   46,   45,   45,   75,   33,
       75,   78,  113,   78,   73,   73,   78,   40,   78,  132,
       47,   76,   76,   47,   95,   88,  208,   47,   47,  170,
      181,   89,   47,   40,   40,   90,   79,   47,   63,   40,
       63,   47,   91,  208,   91,   47,   96,   92,  208,   47,
       40,   93,   47,  113,   94,   40,   47,   81,   82,  107,
       82,   64,  191,   47,  192,   36,   37,   47,   38,   47,
       39,   83,   83,   47,   47,  154,   47,   65,   47,   47,
       47,   85,   47,   47,   47,   87,   47,   47,   47,  153,

       42,   47,   97,   66,  202,   66,  202,   86,   98,   90,
      100,   99,  147,  208,  101,  208,   67,   67,   69,  203,
       69,  208,  102,  208,  113,  116,  208,  208,   72,   47,
       72,   70,   70,   47,  208,  208,  208,  121,  208,  117,
       47,   73,   73,   75,   47,   75,  208,  138,  208,  208,
      208,   78,   78,   78,   78,  107,   76,   76,  129,  208,
      208,   78,   78,   78,   78,   91,  128,   91,   36,   37,
       92,   38,   47,   39,   40,   40,   47,  118,  105,  118,
      107,   46,  120,  208,  208,   84,  178,  186,   47,  122,
       40,   40,   47,   46,  208,  108,   82,   78,   82,   78,

       78,   84,   78,   36,   37,  118,   38,  118,   39,   83,
       83,  112,  104,  112,   47,  103,  113,   47,   47,   85,
       84,   47,  110,   84,  114,  114,   47,   46,   42,  208,
       47,  126,  208,   47,   47,   86,   84,   47,   47,   84,
       47,  111,   47,  123,   47,   47,   47,   47,   28,   47,
      116,   47,   78,   47,   78,  117,   78,   47,   78,   28,
      151,  141,   78,  141,   78,  125,  142,   78,  124,   78,
       47,  143,   28,  127,   47,   40,  144,   47,  208,   40,
      208,   47,   47,  130,  208,   84,   47,  208,  208,  134,
       84,   40,  145,  152,  208,   40,  208,  186,  208,  208,

      112,   84,  112,  133,   47,  113,   84,   44,   47,   44,
      135,  208,  113,  136,  136,   47,   46,  208,   47,   47,
       45,   45,   47,   46,  148,  150,   47,  149,   47,  148,
       47,   47,   47,  208,   78,   47,   78,   78,  208,   78,
       78,  208,   78,  208,   47,   78,  150,   78,   47,  141,
      208,  141,   47,  149,  142,  162,   47,   40,   47,  164,
       40,  164,  168,   84,  155,   46,  208,  208,   84,  208,
       47,  156,  208,   40,   47,  208,   40,  208,  208,   84,
       44,  208,   44,  155,   84,  113,  166,  208,  166,  163,
      208,  167,  157,   45,   45,   47,   46,   47,   78,   47,

       78,   47,   78,  170,   78,  173,   78,   47,   78,   47,
      170,   47,  164,   47,  164,  168,  208,   78,  208,   78,
      178,  166,  170,  166,  208,   84,  167,   47,   64,   84,
      208,   47,  171,  174,  208,  175,   47,   46,  208,  208,
       47,   84,  182,  179,   65,   84,   47,  208,  208,  208,
       47,  176,  171,  182,   47,  188,   47,  143,   47,  180,
       47,  189,  144,   47,   47,   47,   47,   47,   47,   47,
       47,  190,  208,  193,  195,   47,  198,  200,  145,   47,
      208,  202,  208,  202,  201,  201,  195,  202,  208,  204,
      194,   47,  195,   47,  208,   47,  203,   47,  205,  200,

       47,  199,  203,  202,  207,  202,  201,  201,  195,  202,
      208,  204,  178,  208,  195,  197,  206,   47,  203,  208,
      208,   47,  208,  208,  203,  208,  208,  208,   47,  208,
      208,  208,   47,  197,  208,  179,  208,  207,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  180,  208,  208,  208,  197,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   34,   34,  208,  208,  208,
      208,   34,   34,   34,   34,   40,   40,  208,  208,  208,
       40,  208,  208,  208,   40,   47,   47,  208,  208,  208,
      208,  208,   47,   47,   47,   68,   68,  208,  208,  208,

      208,  208,   68,  208,   68,   71,   71,  208,  208,  208,
      208,  208,   71,  208,   71,   74,   74,  208,  208,  208,
      208,  208,   74,  208,   74,   77,   77,  208,  208,  208,
      208,  208,   77,  208,   77,   84,   84,  208,  208,  208,
       84,  208,   84,  208,   84,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  109,  208,  109,  115,  115,  208,
      115,  208,  208,  208,  115,  115,  115,  119,  119,  119,
      119,  119,  208,  119,  119,  119,  119,  119,  137,  137,
      208,  137,  208,  208,  208,  137,  137,  137,  139,  208,
      208,  208,  208,  139,  140,  140,  208,  140,  208,  208,

      208,  140,  140,  140,  146,  146,  208,  208,  208,  208,
      208,  146,  146,  146,  158,  208,  208,  208,  208,  208,
      158,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  187,  187,  208,  208,  208,  208,  187,  196,  208,
      196,  208,  208,  208,  196,  208,  196,    3,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,

      208,  208,  208,  208,  208,  208,  208
    } ;

static const flex_int16_t yy_chk[1008] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
      183,    5,    8,    8,   42,    9,  192,    9,   19,   29,
       29,   10,   19,   10,    9,    5,    9,  184,    9,    9,
       10,    9,   10,   19,   10,   10,  177,   10,   11,   12,
       11,   12,   42,   21,  176,   11,   11,   21,   11,   13,
       11,   13,   12,   12,  183,   12,   31,   31,   14,  175,

       14,   11,   13,   13,   21,   13,   83,   83,  161,   13,
       11,   14,   14,   15,   14,   15,   17,   11,  160,   16,
       17,   16,   14,   17,   20,  158,   15,   15,   20,   15,
      107,  154,   16,   16,   18,   16,  153,   18,   18,   15,
       16,   22,   18,   20,   16,   22,   23,   24,  109,  109,
       23,   24,   25,   36,   25,   36,  185,   22,  185,  107,
       24,   22,   24,   30,  147,   30,   36,   36,   25,   23,
       26,   33,   26,   33,   32,  142,   32,   26,   26,   30,
       26,  139,   26,   32,   37,   32,   37,   32,   32,  138,
       32,   47,   48,   26,   33,   47,   48,   37,   37,   44,

      131,   44,   26,   34,   40,   34,   40,  167,  167,   26,
       33,   38,   34,   38,   34,   44,   34,   34,   39,   34,
       39,   41,  137,   41,   38,   38,   43,   40,   43,  131,
       54,   39,   39,   49,   54,   49,   40,   49,   50,  170,
      170,   49,   50,   40,   41,   50,   41,   55,   63,   43,
       63,   55,   51,   41,   51,   52,   55,   51,   43,   52,
       41,   52,   53,  136,   53,   43,   53,   43,   46,  132,
       46,   63,  191,   51,  191,   46,   46,   51,   46,   56,
       46,   46,   46,   56,   57,  129,   58,   63,   57,   59,
       58,   46,   60,   59,   61,   56,   60,   62,   61,  128,

       46,   62,   57,   66,  202,   66,  202,   46,   57,   58,
       60,   59,  119,   68,   61,   68,   66,   66,   69,  202,
       69,   71,   62,   71,  114,   88,   68,   68,   72,   88,
       72,   69,   69,   94,   71,   71,   74,   94,   74,   89,
       89,   72,   72,   75,   89,   75,   77,  113,   77,   74,
       74,   79,   81,   79,   81,  106,   75,   75,  104,   77,
       77,   78,   84,   78,   84,   91,  103,   91,   78,   78,
       91,   78,   93,   78,   79,   81,   93,  118,   79,  118,
       80,   91,   93,   79,   81,   84,  178,  178,   95,   95,
       79,   81,   95,  118,   84,   81,   82,   85,   82,   85,

       86,   84,   86,   82,   82,   90,   82,   90,   82,   82,
       82,   87,   65,   87,  101,   64,   87,  148,  101,   82,
       85,  148,   85,   86,   87,   87,   90,   87,   82,   85,
       90,  101,   86,   96,   97,   82,   85,   96,   97,   86,
       98,   86,   99,   96,   98,  100,   99,  102,   28,  100,
       97,  102,  105,  123,  105,   98,  108,  123,  108,   27,
      123,  116,  110,  116,  110,  100,  116,  111,   99,  111,
      127,  117,    7,  102,  127,  105,  117,  117,    3,  108,
        0,  117,  116,  105,  105,  110,  116,    0,  108,  110,
      111,  105,  117,  127,  110,  108,  187,  187,    0,  111,

      112,  110,  112,  108,  124,  112,  111,  115,  124,  115,
      111,    0,  115,  112,  112,  120,  112,    0,  121,  120,
      115,  115,  121,  115,  120,  122,  122,  121,  125,  124,
      122,  126,  125,    0,  130,  126,  130,  133,    0,  133,
      134,    0,  134,    0,  150,  135,  126,  135,  150,  141,
        0,  141,  144,  125,  141,  144,  144,  130,  151,  146,
      133,  146,  151,  134,  130,  141,  130,    0,  135,  133,
      145,  134,  134,  130,  145,  146,  133,  135,    0,  134,
      140,    0,  140,  133,  135,  140,  149,    0,  149,  145,
        0,  149,  135,  140,  140,  152,  140,  162,  155,  152,

      155,  162,  156,  155,  156,  162,  157,  149,  157,  163,
      169,  149,  164,  163,  164,  152,    0,  171,    0,  171,
      168,  166,  171,  166,    0,  156,  166,  174,  169,  157,
      155,  174,  156,  163,  156,  164,  168,  166,  157,    0,
      168,  156,  174,  168,  169,  157,  180,    0,    0,  171,
      180,  164,  157,  173,  173,  179,  179,  182,  173,  168,
      179,  180,  182,  182,  188,  189,  193,  182,  188,  189,
      193,  190,    0,  188,  190,  194,  193,  195,  182,  194,
        0,  196,    0,  196,  195,  195,  196,  197,    0,  197,
      189,  198,  197,  199,    0,  198,  196,  199,  198,  201,

      205,  194,  197,  200,  205,  200,  201,  201,  200,  204,
        0,  204,  207,    0,  204,  190,  199,  206,  200,    0,
        0,  206,    0,    0,  204,    0,    0,    0,  207,    0,
        0,    0,  207,  197,    0,  207,    0,  206,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  207,    0,    0,    0,  204,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  210,  210,    0,    0,    0,
        0,  210,  210,  210,  210,  211,  211,    0,    0,    0,
      211,    0,    0,    0,  211,  212,  212,    0,    0,    0,
        0,    0,  212,  212,  212,  213,  213,    0,    0,    0,

        0,    0,  213,    0,  213,  214,  214,    0,    0,    0,
        0,    0,  214,    0,  214,  215,  215,    0,    0,    0,
        0,    0,  215,    0,  215,  216,  216,    0,    0,    0,
        0,    0,  216,    0,  216,  217,  217,    0,    0,    0,
      217,    0,  217,    0,  217,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  219,    0,  219,  220,  220,    0,
      220,    0,    0,    0,  220,  220,  220,  221,  221,  221,
      221,  221,    0,  221,  221,  221,  221,  221,  222,  222,
        0,  222,    0,    0,    0,  222,  222,  222,  223,    0,
        0,    0,    0,  223,  224,  224,    0,  224,    0,    0,

        0,  224,  224,  224,  225,  225,    0,    0,    0,    0,
        0,  225,  225,  225,  226,    0,    0,    0,    0,    0,
      226,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  229,  229,    0,    0,    0,    0,  229,  230,    0,
      230,    0,    0,    0,  230,    0,  230,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,

      208,  208,  208,  208,  208,  208,  208
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main.l"
#line 3 "main.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "microTokens.h"

int line_number = 1;
int if_count = 0;
int if_elif_count = 0;
int if_else_count = 0;
int for_count = 0;
int print_statement_count = 0;
int input_statement_count = 0;
int for_in_count = 0;
int function_statemnt_count = 0;
int type_errors = 0;
int variable_declaration_count = 0;
int return_statement_count = 0;
int add_operation_count = 0;
int minus_operation_count = 0;
int multiply_operation_count = 0;
int divide_operation_count = 0;
int table_declaration_count = 0;

int error_count = 0;
int MAX_ERRORS = 3;

void ret_print(char *token_type);
void yyerror();
#line 768 "lex.yy.c"
#line 769 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 58 "main.l"


#line 989 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 209 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 958 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 60 "main.l"
ret_print("SPACE");
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 61 "main.l"
{ ret_print("T_IF"); if_count++; return T_IF;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 62 "main.l"
{ ret_print("T_ELSE"); return T_ELSE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 63 "main.l"
{ ret_print("T_ELIF"); return T_ELIF; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "main.l"
{ ret_print("T_FOR"); for_count++; return T_FOR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 65 "main.l"
{ ret_print("KEYWORD_RETURN"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 "main.l"
{ ret_print("KEYWORD_INPUT"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 67 "main.l"
{ ret_print("KEYWORD_PRINT"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 "main.l"
{ ret_print("RANGE_KEYWORD"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 69 "main.l"
{ ret_print("DEF_KEYWORD"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "main.l"
{ ret_print("Table Declaration"); table_declaration_count++; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "main.l"
{ ret_print("Return Statement"); return_statement_count++; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "main.l"
{ ret_print("Variable Declaration"); variable_declaration_count++;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "main.l"
{ ret_print("Variable"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "main.l"
{ ret_print("INTEGER"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "main.l"
{ ret_print("FLOAT"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "main.l"
{ ret_print("STRING"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "main.l"
{ ret_print("Print Statement"); print_statement_count++;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 79 "main.l"
{ ret_print("Input Statement"); input_statement_count++;}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 80 "main.l"
{ ret_print("If Statement"); if_count++;}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 81 "main.l"
{ ret_print("Else If Statement"); if_elif_count++;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 82 "main.l"
{ ret_print("Else Statement"); if_else_count++;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 83 "main.l"
{ ret_print("For in Statement"); for_in_count++;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 84 "main.l"
{ ret_print("Function Statement"); function_statemnt_count++;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 85 "main.l"
{ ret_print("Add Operation"); add_operation_count++; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 86 "main.l"
{ ret_print("Minus Operation"); minus_operation_count++; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 87 "main.l"
{ ret_print("Multiply Operation"); multiply_operation_count++; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 88 "main.l"
{ ret_print("Divide Operation"); divide_operation_count++; }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 89 "main.l"
{ line_number += 1; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 90 "main.l"
{ yyerror("Unrecognized character"); type_errors++;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 92 "main.l"
ECHO;
	YY_BREAK
#line 1204 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 209 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 209 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 208);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 92 "main.l"


void ret_print(char *token_type)
{
    printf("Line: %d\t yytext: %s\t token: %s\n",line_number, yytext, token_type);
}

void yyerror(char *message)
{

    printf("Error: \"%s\" in line %d. Token: %s\n", message, line_number, yytext);
    error_count++;

    if (error_count >= MAX_ERRORS) {
        printf("Exceeded maximum error count. Terminating program.\n");
        exit(1);
    }
}


int main(int argc, char *argv[])
{
    yyin = fopen("input.py", "r");
    printf("--------------------------------------------------------------------\n");
    printf("\t\t\tPROGRAM INFORMATION\t\t\t\n");
    printf("--------------------------------------------------------------------\n");
    yylex();
    fclose(yyin);

    printf("\n----------------------------------------------------\n"); 
    printf("\t\tCODE STATISTICS\t\t\n");
    printf("----------------------------------------------------\n");
    printf("|IF Statements|\n");
    printf("---------------------\n");
    printf("IF Statement count: %d\n", if_count);
    printf("IF..ELIF..ELSE.. Statement count: %d\n", if_elif_count);
    printf("IF..ELSE.. Statement count: %d\n", if_else_count);
    printf("\n");
    printf("|FOR Statements|\n");
    printf("---------------------\n");
    printf("FOR Statement count: %d\n", for_in_count);
    printf("\n");
    printf("|User Interaction Statements|\n");
    printf("---------------------\n");
    printf("Number of Print :  %d\n", print_statement_count);
    printf("Number of User Input :  %d\n", input_statement_count);
    printf("\n");
    printf("|Math Statements|\n");
    printf("---------------------\n");
    printf("Add Operations :  %d\n", add_operation_count);
    printf("Minus Operations :  %d\n", minus_operation_count);
    printf("Multiply Operations :  %d\n", multiply_operation_count);
    printf("Divide Operations :  %d\n", divide_operation_count);
    printf("\n");
    printf("|Other Information|\n");
    printf("---------------------\n");
    printf("Functions :  %d\n", function_statemnt_count);
    printf("Variable Declaration :  %d\n", variable_declaration_count);
    printf("Table Declaration :  %d\n", table_declaration_count);
    printf("Return Statement :  %d\n", return_statement_count);

    printf("\n");
    printf("|Program Errors|\n");
    printf("---------------------\n");
    printf("Typing Errors :  %d\n", type_errors);
    printf("\n");
}
    
